#!/usr/bin/env bash
# script that sets the port 80
sudo apt update
sudo apt upgrade -y
sudo apt install nginx -y
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart