#!/usr/bin/env bash
# A script to indicate special numbers from Italy and China

i=1

while [ $i -le 21 ]
do
    case $i in
        5)    echo "bad luck from China"
              ;;
        8)    echo "good luck from China"
              ;;
        18)   echo "bad luck from Italy"
              ;;
        *)    echo $i
              ;;
    esac
    i=$((i + 1))
done


