#!/usr/bin/env bash
# A script to simulate a clock

i=0

while [ $i -le 12 ]
do
    echo "Hour: $i"
    j=1
    while [ $j -lt 60 ]
    do
        echo "$j"
        j=$(( j + 1 ))
    done
    i=$(( i + 1 ))
done
